from __future__ import annotations

from io import BytesIO

from openpyxl import Workbook
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.utils import get_column_letter
from openpyxl.worksheet.table import Table, TableStyleInfo
from openpyxl.worksheet.worksheet import Worksheet

from app.models import FindingRecord
from app.reports.common import RISK_ORDER, CheckSection, ReportData, system_label

NAVY = "1F3A5F"
RISK_FILLS = {
    "High": PatternFill("solid", fgColor="F6D5D5"),
    "Medium": PatternFill("solid", fgColor="FBE0D4"),
    "Low": PatternFill("solid", fgColor="FDEFCC"),
    "Informational": PatternFill("solid", fgColor="ECEAE6"),
}
SHEET_NAMES = {
    "terminated_active_access": "Terminated Active Access",
    "late_revocation": "Late Revocation",
    "orphan_accounts": "Orphan Accounts",
    "generic_shared_accounts": "Generic Shared Accounts",
    "privileged_access": "Privileged Access",
    "sod_conflicts": "SoD Conflicts",
    "dormant_accounts": "Dormant Accounts",
}

TITLE = Font(bold=True, size=16, color=NAVY)
SECTION = Font(bold=True, size=12, color=NAVY)
BOLD = Font(bold=True)
HEADER_FONT = Font(bold=True, color="FFFFFF")
HEADER_FILL = PatternFill("solid", fgColor=NAVY)
LABEL_FILL = PatternFill("solid", fgColor="F1F0EC")
WRAP_TOP = Alignment(wrap_text=True, vertical="top")
THIN = Side(style="thin", color="D9D7D0")
BOX = Border(left=THIN, right=THIN, top=THIN, bottom=THIN)


def sheet_name(section: CheckSection) -> str:
    name = SHEET_NAMES.get(section.check.code, section.check.name)
    return "".join(c for c in name if c not in r"[]:*?/\\")[:31]


def _header_row(ws: Worksheet, row: int, headers: list[str]) -> None:
    for col, text in enumerate(headers, start=1):
        cell = ws.cell(row=row, column=col, value=text)
        cell.font = HEADER_FONT
        cell.fill = HEADER_FILL
        cell.alignment = Alignment(vertical="center", wrap_text=True)
        cell.border = BOX


def _widths(ws: Worksheet, widths: list[int]) -> None:
    for i, w in enumerate(widths, start=1):
        ws.column_dimensions[get_column_letter(i)].width = w


def _findings_table(ws: Worksheet, start_row: int, findings: list[FindingRecord],
                    table_name: str, include_check: bool) -> None:
    headers = ["Finding ID", "Risk", *(["Check"] if include_check else []),
               "System", "Employee ID", "Username", "Details", "Detected at (UTC)"]
    _header_row(ws, start_row, headers)
    for r, f in enumerate(findings, start=start_row + 1):
        values = [f.finding_id, f.risk_rating, *([f.check_name] if include_check else []),
                  system_label(f.system), f.employee_id or "", f.username, f.details,
                  f.detected_at.replace(tzinfo=None)]
        for c, value in enumerate(values, start=1):
            cell = ws.cell(row=r, column=c, value=value)
            cell.alignment = WRAP_TOP
            cell.border = BOX
        ws.cell(row=r, column=2).fill = RISK_FILLS.get(f.risk_rating, LABEL_FILL)
        ws.cell(row=r, column=len(headers)).number_format = "yyyy-mm-dd hh:mm"

    end_row = start_row + len(findings)
    ref = f"A{start_row}:{get_column_letter(len(headers))}{end_row}"
    table = Table(displayName=table_name, ref=ref)
    table.tableStyleInfo = TableStyleInfo(name="TableStyleLight1", showRowStripes=False)
    ws.add_table(table)
    ws.freeze_panes = ws.cell(row=start_row + 1, column=1)

    widths = [11, 13, *([28] if include_check else []), 18, 13, 26, 70, 17]
    _widths(ws, widths)


def _summary_sheet(ws: Worksheet, data: ReportData) -> None:
    ws.title = "Summary"
    review, dataset = data.review, data.dataset
    ws["A1"] = data.title
    ws["A1"].font = TITLE
    ws["A2"] = "ITGC user access review - generated by AccessGuard"
    ws["A2"].font = Font(italic=True, color="52514E")

    meta = [
        ("Review ID", f"#{review.id}"),
        ("Data as of", data.as_of),
        ("Review run", f"{review.run_at:%d %b %Y %H:%M} UTC by {review.run_by}"),
        ("Report generated", f"{data.generated_at:%d %b %Y %H:%M} UTC"),
        ("HR records reviewed", dataset.hr_employee_count),
        ("Systems in scope", ", ".join(
            f"{system_label(s)} ({dataset.account_counts.get(s, 0)} accounts)" for s in review.systems)),
        ("Total findings", len(data.findings)),
    ]
    row = 4
    for label, value in meta:
        ws.cell(row=row, column=1, value=label).font = BOLD
        ws.cell(row=row, column=2, value=value).alignment = Alignment(horizontal="left")
        row += 1

    row += 1
    ws.cell(row=row, column=1, value="Findings by risk").font = SECTION
    row += 1
    _header_row(ws, row, ["Risk", "Findings", "% of total"])
    total = len(data.findings) or 1
    for risk in RISK_ORDER:
        row += 1
        count = data.by_risk[risk]
        ws.cell(row=row, column=1, value=risk).fill = RISK_FILLS[risk]
        ws.cell(row=row, column=2, value=count)
        pct = ws.cell(row=row, column=3, value=count / total)
        pct.number_format = "0%"
        for c in range(1, 4):
            ws.cell(row=row, column=c).border = BOX

    row += 2
    ws.cell(row=row, column=1, value="Findings by check").font = SECTION
    row += 1
    _header_row(ws, row, ["Check", *RISK_ORDER, "Total", "Worksheet"])
    for section in data.sections:
        row += 1
        by_risk = section.by_risk
        ws.cell(row=row, column=1, value=section.check.name)
        for c, risk in enumerate(RISK_ORDER, start=2):
            ws.cell(row=row, column=c, value=by_risk.get(risk, 0))
        ws.cell(row=row, column=6, value=len(section.findings)).font = BOLD
        link = ws.cell(row=row, column=7, value=sheet_name(section))
        link.hyperlink = f"#'{sheet_name(section)}'!A1"
        link.font = Font(color="2A78D6", underline="single")
        for c in range(1, 8):
            ws.cell(row=row, column=c).border = BOX

    row += 2
    ws.cell(row=row, column=1, value="Findings by system").font = SECTION
    row += 1
    _header_row(ws, row, ["System", "Findings"])
    by_system: dict[str, int] = {}
    for f in data.findings:
        by_system[f.system] = by_system.get(f.system, 0) + 1
    for system, count in sorted(by_system.items(), key=lambda kv: -kv[1]):
        row += 1
        ws.cell(row=row, column=1, value=system_label(system)).border = BOX
        ws.cell(row=row, column=2, value=count).border = BOX

    _widths(ws, [34, 16, 14, 10, 15, 10, 26])


def _check_sheet(ws: Worksheet, section: CheckSection, data: ReportData) -> None:
    ws["A1"] = f"{section.number}. {section.check.name}"
    ws["A1"].font = TITLE
    breakdown = ", ".join(f"{c} {r}" for r, c in section.by_risk.items())
    ws["A2"] = f"{len(section.findings)} finding(s)" + (f": {breakdown}" if breakdown else "")
    ws["A2"].font = Font(italic=True, color="52514E")

    blocks = [
        ("Condition", section.condition_text(data.as_of)),
        ("Criteria", section.check.criteria),
        ("Risk / Impact", section.check.impact),
        ("Recommendation", section.check.recommendation),
    ]
    row = 4
    for label, text in blocks:
        label_cell = ws.cell(row=row, column=1, value=label)
        label_cell.font = BOLD
        label_cell.fill = LABEL_FILL
        label_cell.alignment = WRAP_TOP
        ws.merge_cells(start_row=row, start_column=2, end_row=row, end_column=7)
        text_cell = ws.cell(row=row, column=2, value=text)
        text_cell.alignment = WRAP_TOP
        ws.row_dimensions[row].height = 15 * max(1, -(-len(text) // 140))
        row += 1

    row += 1
    if section.findings:
        _findings_table(ws, row, section.findings, f"tbl_{section.check.code}", include_check=False)
        ws.column_dimensions["A"].width = 16
    else:
        ws.cell(row=row, column=1, value="No exceptions noted.").font = Font(italic=True)
        _widths(ws, [16, 13, 18, 13, 26, 70, 17])


def build_excel(data: ReportData) -> bytes:
    wb = Workbook()
    _summary_sheet(wb.active, data)
    for section in data.sections:
        _check_sheet(wb.create_sheet(sheet_name(section)), section, data)
    all_ws = wb.create_sheet("All Findings")
    if data.findings:
        _findings_table(all_ws, 1, data.findings, "tbl_all_findings", include_check=True)
    else:
        all_ws["A1"] = "No exceptions noted."
    buffer = BytesIO()
    wb.save(buffer)
    return buffer.getvalue()
