from __future__ import annotations

from io import BytesIO
from xml.sax.saxutils import escape

from reportlab.graphics.shapes import Drawing, Line, Rect, String
from reportlab.lib import colors
from reportlab.lib.enums import TA_LEFT
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas
from reportlab.platypus import (
    BaseDocTemplate,
    CondPageBreak,
    Frame,
    KeepTogether,
    ListFlowable,
    ListItem,
    NextPageTemplate,
    PageBreak,
    PageTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
)

from app.reports.common import RISK_ORDER, CheckSection, ReportData, system_label

NAVY = colors.HexColor("#1F3A5F")
ACCENT = colors.HexColor("#2A78D6")
INK = colors.HexColor("#0B0B0B")
INK_2 = colors.HexColor("#52514E")
MUTED = colors.HexColor("#898781")
HAIRLINE = colors.HexColor("#D9D7D0")
LABEL_BG = colors.HexColor("#F1F0EC")
RISK_TINT = {
    "High": colors.HexColor("#F6D5D5"),
    "Medium": colors.HexColor("#FBE0D4"),
    "Low": colors.HexColor("#FDEFCC"),
    "Informational": colors.HexColor("#ECEAE6"),
}

MARGIN = 18 * mm

STYLES = {
    "cover_title": ParagraphStyle("cover_title", fontName="Helvetica-Bold", fontSize=28, leading=34, textColor=NAVY),
    "cover_sub": ParagraphStyle("cover_sub", fontName="Helvetica", fontSize=13, leading=18, textColor=INK_2),
    "h1": ParagraphStyle("h1", fontName="Helvetica-Bold", fontSize=16, leading=20, textColor=NAVY,
                         spaceBefore=4, spaceAfter=8),
    "h2": ParagraphStyle("h2", fontName="Helvetica-Bold", fontSize=12, leading=15, textColor=NAVY,
                         spaceBefore=12, spaceAfter=2),
    "meta": ParagraphStyle("meta", fontName="Helvetica", fontSize=9, leading=12, textColor=INK_2, spaceAfter=6),
    "body": ParagraphStyle("body", fontName="Helvetica", fontSize=9.5, leading=13.5, textColor=INK,
                           alignment=TA_LEFT, spaceAfter=6),
    "cell": ParagraphStyle("cell", fontName="Helvetica", fontSize=8.5, leading=11.5, textColor=INK),
    "cell_bold": ParagraphStyle("cell_bold", fontName="Helvetica-Bold", fontSize=8.5, leading=11.5, textColor=INK),
    "small": ParagraphStyle("small", fontName="Helvetica", fontSize=7.5, leading=9.5, textColor=INK),
    "small_head": ParagraphStyle("small_head", fontName="Helvetica-Bold", fontSize=7.5, leading=9.5,
                                 textColor=colors.white),
    "head": ParagraphStyle("head", fontName="Helvetica-Bold", fontSize=8.5, leading=11.5, textColor=colors.white),
}


def P(text, style: str = "body") -> Paragraph:
    return Paragraph(escape(str(text)), STYLES[style])


def _grid_style(header: bool = True) -> list:
    style = [
        ("GRID", (0, 0), (-1, -1), 0.5, HAIRLINE),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("LEFTPADDING", (0, 0), (-1, -1), 5),
        ("RIGHTPADDING", (0, 0), (-1, -1), 5),
    ]
    if header:
        style.append(("BACKGROUND", (0, 0), (-1, 0), NAVY))
    return style


def _make_canvas(title: str):
    class NumberedCanvas(canvas.Canvas):
        """Defers drawing headers/footers until the total page count is known."""

        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            self._pages = []

        def showPage(self):
            self._pages.append(dict(self.__dict__))
            self._startPage()

        def save(self):
            total = len(self._pages)
            for number, state in enumerate(self._pages, start=1):
                self.__dict__.update(state)
                if number > 1:
                    self._chrome(number, total)
                super().showPage()
            super().save()

        def _chrome(self, number: int, total: int):
            width, height = self._pagesize
            self.setStrokeColor(HAIRLINE)
            self.setLineWidth(0.5)
            self.line(MARGIN, height - 12 * mm, width - MARGIN, height - 12 * mm)
            self.line(MARGIN, 12 * mm, width - MARGIN, 12 * mm)
            self.setFont("Helvetica", 8)
            self.setFillColor(MUTED)
            self.drawString(MARGIN, height - 10 * mm, f"AccessGuard  |  {title}")
            self.drawRightString(width - MARGIN, height - 10 * mm, "Confidential")
            self.drawString(MARGIN, 8 * mm, "Generated by AccessGuard - ITGC user access review automation")
            self.drawRightString(width - MARGIN, 8 * mm, f"Page {number} of {total}")

    return NumberedCanvas


def _draw_cover(c: canvas.Canvas, _doc) -> None:
    width, height = A4
    c.saveState()
    c.setFillColor(NAVY)
    c.rect(0, height - 38 * mm, width, 38 * mm, stroke=0, fill=1)
    c.setFillColor(ACCENT)
    c.rect(0, height - 40 * mm, width, 2 * mm, stroke=0, fill=1)
    # Shield mark
    x, y, s = MARGIN, height - 30 * mm, 0.9 * mm
    path = c.beginPath()
    path.moveTo(x + 12 * s, y + 22 * s)
    path.lineTo(x + 4 * s, y + 19 * s)
    path.lineTo(x + 4 * s, y + 13 * s)
    path.curveTo(x + 4 * s, y + 8 * s, x + 7.4 * s, y + 3.4 * s, x + 12 * s, y + 2 * s)
    path.curveTo(x + 16.6 * s, y + 3.4 * s, x + 20 * s, y + 8 * s, x + 20 * s, y + 13 * s)
    path.lineTo(x + 20 * s, y + 19 * s)
    path.close()
    c.setFillColor(colors.white)
    c.drawPath(path, stroke=0, fill=1)
    c.setFont("Helvetica-Bold", 16)
    c.drawString(x + 24 * s, y + 9 * s, "AccessGuard")
    c.setFont("Helvetica", 9)
    c.setFillColor(colors.HexColor("#C9D6E8"))
    c.drawString(x + 24 * s, y + 3 * s, "ITGC user access review automation")
    c.setFillColor(MUTED)
    c.setFont("Helvetica", 8)
    c.drawString(MARGIN, 14 * mm, "CONFIDENTIAL - prepared for internal audit and IT management. Do not distribute.")
    c.restoreState()


def _cover(data: ReportData) -> list:
    review, dataset = data.review, data.dataset
    rows = [
        ("Organisation", data.organization),
        ("Engagement", "IT General Controls (ITGC) - Logical access: periodic user access review"),
        ("Review date (data as of)", data.as_of),
        ("Scope - systems covered", ", ".join(
            f"{system_label(s)} ({dataset.account_counts.get(s, 0)} accounts)" for s in review.systems)),
        ("HR master records", f"{dataset.hr_employee_count}"),
        ("Review reference", f"Review #{review.id} (dataset #{dataset.id})"),
        ("Prepared by", f"{review.run_by}, run on {review.run_at:%d %b %Y %H:%M} UTC"),
        ("Report generated", f"{data.generated_at:%d %b %Y %H:%M} UTC"),
    ]
    table = Table([[P(k, "cell_bold"), P(v, "cell")] for k, v in rows], colWidths=[50 * mm, 110 * mm])
    table.setStyle(TableStyle([
        ("LINEBELOW", (0, 0), (-1, -1), 0.5, HAIRLINE),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("LEFTPADDING", (0, 0), (-1, -1), 0),
    ]))
    return [
        Spacer(1, 45 * mm),
        Paragraph(escape(data.title), STYLES["cover_title"]),
        Spacer(1, 4 * mm),
        P("ITGC User Access Review Report", "cover_sub"),
        Spacer(1, 14 * mm),
        table,
        NextPageTemplate("portrait"),
        PageBreak(),
    ]


def _risk_table(data: ReportData) -> Table:
    total = len(data.findings) or 1
    rows = [[P("Risk rating", "head"), P("Findings", "head"), P("% of total", "head")]]
    for risk in RISK_ORDER:
        count = data.by_risk[risk]
        rows.append([P(risk, "cell_bold"), P(count, "cell"), P(f"{count / total:.0%}", "cell")])
    rows.append([P("Total", "cell_bold"), P(len(data.findings), "cell_bold"), P("100%", "cell_bold")])
    table = Table(rows, colWidths=[45 * mm, 30 * mm, 30 * mm], hAlign="LEFT")
    style = _grid_style()
    for i, risk in enumerate(RISK_ORDER, start=1):
        style.append(("BACKGROUND", (0, i), (0, i), RISK_TINT[risk]))
    style.append(("BACKGROUND", (0, len(rows) - 1), (-1, len(rows) - 1), LABEL_BG))
    table.setStyle(TableStyle(style))
    return table


def _check_table(data: ReportData) -> Table:
    rows = [[P("Check", "head"), *[P(r if r != "Informational" else "Info.", "head") for r in RISK_ORDER],
             P("Total", "head")]]
    for section in data.sections:
        by_risk = section.by_risk
        rows.append([P(f"{section.number}. {section.check.name}", "cell"),
                     *[P(by_risk.get(r, 0) or "-", "cell") for r in RISK_ORDER],
                     P(len(section.findings), "cell_bold")])
    table = Table(rows, colWidths=[74 * mm, 18 * mm, 18 * mm, 18 * mm, 18 * mm, 18 * mm], hAlign="LEFT")
    table.setStyle(TableStyle(_grid_style()))
    return table


def _bar_chart(data: ReportData, width: float) -> Drawing:
    """Single-series horizontal bars (one hue), value at each bar tip."""
    items = sorted(((s.check.name, len(s.findings)) for s in data.sections), key=lambda kv: -kv[1])
    label_w, value_w, bar_h, gap = 62 * mm, 10 * mm, 9, 7
    height = len(items) * (bar_h + gap) + 8
    drawing = Drawing(width, height)
    track = width - label_w - value_w
    peak = max((v for _, v in items), default=0) or 1
    drawing.add(Line(label_w, 2, label_w, height - 4, strokeColor=HAIRLINE, strokeWidth=0.5))
    for i, (label, value) in enumerate(items):
        y = height - (i + 1) * (bar_h + gap)
        drawing.add(String(0, y + 2, label, fontName="Helvetica", fontSize=8, fillColor=INK_2))
        bar_w = max(track * value / peak, 1.5 if value else 0)
        drawing.add(Rect(label_w, y, bar_w, bar_h, fillColor=ACCENT, strokeColor=None, rx=0, ry=0))
        drawing.add(String(label_w + bar_w + 4, y + 2, str(value), fontName="Helvetica-Bold",
                           fontSize=8, fillColor=INK))
    return drawing


def _executive_summary(data: ReportData, content_width: float) -> list:
    review = data.review
    by_risk = data.by_risk
    total = len(data.findings)
    intro = (
        f"AccessGuard reconciled {data.dataset.hr_employee_count} HR master records against "
        f"{data.total_accounts} user accounts across {len(review.systems)} in-scope systems "
        f"({', '.join(data.systems)}), using data extracted as of {data.as_of}. Seven automated checks were "
        f"performed covering leaver access, revocation timeliness, account ownership, shared accounts, "
        f"privileged access, segregation of duties and dormancy."
    )
    result = (
        f"In total {total} exceptions were identified: {by_risk['High']} High, {by_risk['Medium']} Medium, "
        f"{by_risk['Low']} Low and {by_risk['Informational']} Informational."
    )

    ranked = sorted(
        (s for s in data.sections if s.findings),
        key=lambda s: (RISK_ORDER.index(s.rating), -len(s.findings)),
    )
    observations = ListFlowable(
        [ListItem(P(f"{s.check.name}: {len(s.findings)} exception(s) "
                    f"({', '.join(f'{c} {r}' for r, c in s.by_risk.items())}). "
                    f"{s.check.impact.split('. ')[0].rstrip('.')}.", "body"), leftIndent=10)
         for s in ranked if s.rating in ("High", "Medium")],
        bulletType="bullet", bulletFontSize=7, leftIndent=10,
    )
    return [
        P("1. Executive summary", "h1"),
        P(intro), P(result),
        P("Findings by risk rating", "h2"), _risk_table(data),
        P("Key observations", "h2"), observations,
        CondPageBreak(90 * mm),
        P("Findings by check", "h2"), _check_table(data), Spacer(1, 5 * mm),
        _bar_chart(data, content_width),
        PageBreak(),
    ]


def _section_block(section: CheckSection, data: ReportData, content_width: float) -> list:
    n = len(section.findings)
    rating = section.rating or "No exceptions"
    heading = P(f"2.{section.number} {section.check.name}", "h2")
    meta = Paragraph(
        f"Rating: <b>{escape(rating)}</b> &nbsp;|&nbsp; Exceptions: <b>{n}</b>"
        + (" &nbsp;|&nbsp; Full list: Appendix A" if n else ""),
        STYLES["meta"],
    )

    condition = [P(section.condition_text(data.as_of), "cell")]
    examples = section.findings[:3]
    if examples:
        condition.append(Spacer(1, 3))
        condition.append(P("Examples:", "cell_bold"))
        condition += [P(f"- {f.finding_id} ({system_label(f.system)}): {f.details}", "cell") for f in examples]

    rows = [
        [P("Condition", "cell_bold"), condition],
        [P("Criteria", "cell_bold"), P(section.check.criteria, "cell")],
        [P("Risk / Impact", "cell_bold"), P(section.check.impact, "cell")],
        [P("Recommendation", "cell_bold"), P(section.check.recommendation, "cell")],
    ]
    table = Table(rows, colWidths=[32 * mm, content_width - 32 * mm])
    style = _grid_style(header=False) + [("BACKGROUND", (0, 0), (0, -1), LABEL_BG)]
    if section.rating:
        style.append(("LINEBEFORE", (0, 0), (0, -1), 3, RISK_TINT[section.rating]))
    table.setStyle(TableStyle(style))
    return [KeepTogether([heading, meta, table]), Spacer(1, 4 * mm)]


def _detailed_findings(data: ReportData, content_width: float) -> list:
    flow = [
        P("2. Detailed findings", "h1"),
        P("Each check is reported in audit format: the condition found, the criteria it was tested "
          "against, the risk it creates, and the recommended remediation. "
          + ("Every individual exception is listed in Appendix A." if data.findings
             else "No exceptions were identified in this review.")),
    ]
    for section in data.sections:
        flow += _section_block(section, data, content_width)
    return flow


def _appendix(data: ReportData, content_width: float) -> list:
    headers = ["ID", "Risk", "Check", "System", "Employee", "Username", "Details"]
    fixed = [15 * mm, 20 * mm, 42 * mm, 30 * mm, 19 * mm, 38 * mm]
    widths = fixed + [content_width - sum(fixed)]
    rows = [[P(h, "small_head") for h in headers]]
    style = _grid_style()
    for i, f in enumerate(data.findings, start=1):
        rows.append([
            P(f.finding_id, "small"), P(f.risk_rating, "small"), P(f.check_name, "small"),
            P(system_label(f.system), "small"), P(f.employee_id or "-", "small"),
            Paragraph("<br/>".join(escape(u) for u in f.username.split(", ")), STYLES["small"]),
            P(f.details, "small"),
        ])
        style.append(("BACKGROUND", (1, i), (1, i), RISK_TINT.get(f.risk_rating, LABEL_BG)))
    table = Table(rows, colWidths=widths, repeatRows=1)
    table.setStyle(TableStyle(style + [("TOPPADDING", (0, 0), (-1, -1), 3), ("BOTTOMPADDING", (0, 0), (-1, -1), 3)]))
    return [
        NextPageTemplate("landscape"),
        PageBreak(),
        P("Appendix A - Full exception list", "h1"),
        P(f"All {len(data.findings)} exceptions from review #{data.review.id}, in finding ID order "
          f"(grouped by check). Data as of {data.as_of}.", "meta"),
        table,
    ]


def build_pdf(data: ReportData) -> bytes:
    buffer = BytesIO()
    portrait_w, portrait_h = A4
    land_w, land_h = landscape(A4)
    top, bottom = 18 * mm, 18 * mm

    doc = BaseDocTemplate(buffer, pagesize=A4, title=data.title, author="AccessGuard",
                          subject="ITGC User Access Review", leftMargin=MARGIN, rightMargin=MARGIN)
    portrait_frame = Frame(MARGIN, bottom, portrait_w - 2 * MARGIN, portrait_h - top - bottom, id="portrait")
    land_frame = Frame(MARGIN, bottom, land_w - 2 * MARGIN, land_h - top - bottom, id="landscape")
    doc.addPageTemplates([
        PageTemplate(id="cover", frames=[portrait_frame], onPage=_draw_cover, pagesize=A4),
        PageTemplate(id="portrait", frames=[portrait_frame], pagesize=A4),
        PageTemplate(id="landscape", frames=[land_frame], pagesize=landscape(A4)),
    ])

    content_width = portrait_w - 2 * MARGIN
    story = (
        _cover(data)
        + _executive_summary(data, content_width)
        + _detailed_findings(data, content_width)
        + (_appendix(data, land_w - 2 * MARGIN) if data.findings else [])
    )
    doc.build(story, canvasmaker=_make_canvas(data.title))
    return buffer.getvalue()
